services:
  servicio-1:
    build: ./servicio-1/
    ports:
      - 8081:8080
    depends_on:
      - mosquitto
    command: python -u main.py

  servicio-2:
    build: ./servicio-2/
    ports:
      - 8082:8080
    depends_on:
      - mosquitto
      - influx
    command: python -u main.py

  servicio-3:
    build: ./servicio-3/
    ports:
      - 8083:8080
    depends_on:
      mysql:
        condition: service_healthy
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    # volumes:
    #   - ./servicio-3/src:/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=tecnoandina
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
    volumes:
      - ./eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mysql:
    image: mysql:8
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tecnoandina
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  influx:
    image: influxdb:alpine
    volumes:
      - influxdata:/var/lib/influxdb
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxadmin
      - DOCKER_INFLUXDB_INIT_ORG=tecnoandina
      - DOCKER_INFLUXDB_INIT_BUCKET=system

  front:
    build: ./front/
    ports:
      - 8001:8000
    depends_on:
      - servicio-3
    command: python -u manage.py runserver 0.0.0.0:8000

volumes:
  mysqldata:
  influxdata: